FROM oven/bun:1

WORKDIR /usr/src/app

ARG DATABASE_URL

# Copy dependency files first for better caching
COPY ./package.json ./turbo.json ./bun.lock ./
COPY ./packages ./packages
COPY ./apps/http-server ./apps/http-server

RUN bun install

COPY . .

RUN bun run db:migrate

EXPOSE 3000

CMD ["bun", "run", "start:http-server"]